# Generated by Django 5.1.3 on 2024-12-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='requests_used',
            field=models.IntegerField(default=0),
        ),
    ]
