# Generated by Django 5.1.3 on 2024-12-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0002_developerprofile_last_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='last_reset',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='requests_used',
        ),
        migrations.CreateModel(
            name='DeveloperActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['developer', 'timestamp'], name='developer_p_develop_88242e_idx')],
            },
        ),
    ]
